from .aspect_ratio import NODE_CLASS_MAPPINGS as ASPECTRATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASPECTRATIO_NODE_DISPLAY_NAMES
from .aspect_ratio_advanced import NODE_CLASS_MAPPINGS as ASPECTRATIOADV_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as ASPECTRATIOADV_NODE_DISPLAY_NAMES
from .FluxStart import NODE_CLASS_MAPPINGS as FLUXSTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLUXSTART_NODE_DISPLAY_NAMES
from .SDXLStart import NODE_CLASS_MAPPINGS as SDXLSTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SDXLSTART_NODE_DISPLAY_NAMES
from .SD35Start import NODE_CLASS_MAPPINGS as SD35START_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SD35START_NODE_DISPLAY_NAMES
from .QwenImageStart import NODE_CLASS_MAPPINGS as QWENIMAGESTART_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as QWENIMAGESTART_NODE_DISPLAY_NAMES
from .starupscale import NODE_CLASS_MAPPINGS as STARUPSCALE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARUPSCALE_NODE_DISPLAY_NAMES
from .starwilds import NODE_CLASS_MAPPINGS as STARWILDS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWILDS_NODE_DISPLAY_NAMES
from .starwildsadv import NODE_CLASS_MAPPINGS as STARWILDSADV_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWILDSADV_NODE_DISPLAY_NAMES
from .fluxstarsampler import NODE_CLASS_MAPPINGS as FLUXSTARSAMPLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as FLUXSTARSAMPLER_NODE_DISPLAY_NAMES
from .star_conditioning_io import NODE_CLASS_MAPPINGS as STARCOND_IO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARCOND_IO_NODE_DISPLAY_NAMES
from .star_detailenhancer import NODE_CLASS_MAPPINGS as STARDETAILENHANCER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDETAILENHANCER_NODE_DISPLAY_NAMES
from .star_infiniteyou_face_swap_mod import NODE_CLASS_MAPPINGS as STARINFINITEYOU_FACESWAP_MOD_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_FACESWAP_MOD_NODE_DISPLAY_NAMES
from .star_infiniteyou_patch import NODE_CLASS_MAPPINGS as STARINFINITEYOU_PATCH_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_PATCH_NODE_DISPLAY_NAMES
from .star_infiniteyou_advanced_patch_maker import NODE_CLASS_MAPPINGS as STARINFINITEYOU_ADV_PATCHMAKER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_ADV_PATCHMAKER_NODE_DISPLAY_NAMES
from .sdstarsampler import NODE_CLASS_MAPPINGS as SDSTARSAMPLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SDSTARSAMPLER_NODE_DISPLAY_NAMES
from .StarFluxFiller import NODE_CLASS_MAPPINGS as STARFLUXFILLER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARFLUXFILLER_NODE_DISPLAY_NAMES
from .detailstardaemon import NODE_CLASS_MAPPINGS as DETAILSTARDAEMON_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DETAILSTARDAEMON_NODE_DISPLAY_NAMES
from .starinfiniteyou import NODE_CLASS_MAPPINGS as STARINFINITEYOU_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARINFINITEYOU_NODE_DISPLAY_NAMES
from .starlatentinput import NODE_CLASS_MAPPINGS as STARLATENTINPUT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLATENTINPUT_NODE_DISPLAY_NAMES
from .StarLatentInput2 import NODE_CLASS_MAPPINGS as STARLATENTINPUT2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLATENTINPUT2_NODE_DISPLAY_NAMES
from .StarImage2Latent import NODE_CLASS_MAPPINGS as STARIMAGE2LATENT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARIMAGE2LATENT_NODE_DISPLAY_NAMES
from .StarNode import NODE_CLASS_MAPPINGS as STARNODE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNODE_NODE_DISPLAY_NAMES
from .StarNode2 import NODE_CLASS_MAPPINGS as STARNODE2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNODE2_NODE_DISPLAY_NAMES
from .startextfilter import NODE_CLASS_MAPPINGS as STARTEXTFILTER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTFILTER_NODE_DISPLAY_NAMES
from .stargridcomposer import NODE_CLASS_MAPPINGS as STARGRIDCOMPOSER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARGRIDCOMPOSER_NODE_DISPLAY_NAMES
from .stargridbatchers import NODE_CLASS_MAPPINGS as STARGRIDBATCHERS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARGRIDBATCHERS_NODE_DISPLAY_NAMES
from .startextinput import NODE_CLASS_MAPPINGS as STARTEXTINPUT_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTINPUT_NODE_DISPLAY_NAMES
from .starfaceloader import NODE_CLASS_MAPPINGS as STARFACELOADER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARFACELOADER_NODE_DISPLAY_NAMES
from .StarDivisibleDimension import NODE_CLASS_MAPPINGS as STARDIVISIBLEDIMENSION_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDIVISIBLEDIMENSION_NODE_DISPLAY_NAMES
from .StarNewsScraper import NODE_CLASS_MAPPINGS as STARNEWS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARNEWS_NODE_DISPLAY_NAMES
from .StarLora import NODE_CLASS_MAPPINGS as STARLORA_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARLORA_NODE_DISPLAY_NAMES
from .StarPSDSaver import NODE_CLASS_MAPPINGS as STARPSDSAVER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPSDSAVER_NODE_DISPLAY_NAMES
from .StarPSDSaver2 import NODE_CLASS_MAPPINGS as STARPSDSAVER2_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPSDSAVER2_NODE_DISPLAY_NAMES
from .startextstorage import NODE_CLASS_MAPPINGS as STARTEXTSTORAGE_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARTEXTSTORAGE_NODE_DISPLAY_NAMES
from .starwatermark import NODE_CLASS_MAPPINGS as STARWATERMARK_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARWATERMARK_NODE_DISPLAY_NAMES
from .StarDenoiseSlider import NODE_CLASS_MAPPINGS as STARDENOISESLIDER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARDENOISESLIDER_NODE_DISPLAY_NAMES
from .starsamplersettings_nodes import NODE_CLASS_MAPPINGS as STARSAMPLERSETTINGS_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSAMPLERSETTINGS_NODE_DISPLAY_NAMES
from .StarPaletteExtractor import NODE_CLASS_MAPPINGS as STARPALETTEEXTRACTOR_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARPALETTEEXTRACTOR_NODE_DISPLAY_NAMES
from .StarShowLastFrame import NODE_CLASS_MAPPINGS as STARSHOWLASTFRAME_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSHOWLASTFRAME_NODE_DISPLAY_NAMES
from .StarAspectVideoRatio import NODE_CLASS_MAPPINGS as STARASPECTVIDEORATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES
from .StarShowLastFrame import NODE_CLASS_MAPPINGS as STARSHOWLASTFRAME_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARSHOWLASTFRAME_NODE_DISPLAY_NAMES
from .StarAspectVideoRatio import NODE_CLASS_MAPPINGS as STARASPECTVIDEORATIO_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES
from .star_random_image_loader import NODE_CLASS_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .star_save_panorama_jpeg import NODE_CLASS_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS
from .star_frame_from_video import NODE_CLASS_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS
from .star_image_loader_1by1 import NODE_CLASS_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS
from .star_icon_exporter import NODE_CLASS_MAPPINGS as STAR_ICON_EXPORTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_ICON_EXPORTER_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_image_ratio import NODE_CLASS_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_wan_ratio import NODE_CLASS_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS
from .star_apply_overlay_depth import NODE_CLASS_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_image_edit_inputs import NODE_CLASS_MAPPINGS as STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_edit_encoder import NODE_CLASS_MAPPINGS as STAR_QWEN_EDIT_ENCODER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_EDIT_ENCODER_NODE_DISPLAY_NAME_MAPPINGS
from .star_image_edit_qwen_kontext import NODE_CLASS_MAPPINGS as STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_DISPLAY_NAME_MAPPINGS
from .star_save_folder_string import NODE_CLASS_MAPPINGS as STAR_SAVE_FOLDER_STRING_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAVE_FOLDER_STRING_NODE_DISPLAY_NAME_MAPPINGS
from .star_ollama_sysprompter_jc import NODE_CLASS_MAPPINGS as STAR_OLLAMA_SYSPROMPTER_JC_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_OLLAMA_SYSPROMPTER_JC_NODE_DISPLAY_NAME_MAPPINGS
from .star_nano_banana import NODE_CLASS_MAPPINGS as STAR_NANO_BANANA_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS
from .star_duplicate_model_finder import NODE_CLASS_MAPPINGS as STAR_DUPLICATE_MODEL_FINDER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_DUPLICATE_MODEL_FINDER_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_edit_plus_conditioner import NODE_CLASS_MAPPINGS as STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_rebalance_prompter import NODE_CLASS_MAPPINGS as STAR_QWEN_REBALANCE_PROMPTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_REBALANCE_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS
from .star_qwen_regional_prompter import NODE_CLASS_MAPPINGS as STAR_QWEN_REGIONAL_PROMPTER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_QWEN_REGIONAL_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS
from .star_sampler import NODE_CLASS_MAPPINGS as STAR_SAMPLER_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SAMPLER_NODE_DISPLAY_NAME_MAPPINGS
from .star_simple_filters import NODE_CLASS_MAPPINGS as STAR_SIMPLE_FILTERS_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as STAR_SIMPLE_FILTERS_NODE_DISPLAY_NAME_MAPPINGS

import os
import shutil
import sys

# Try to import folder_paths from ComfyUI
try:
    import folder_paths
except ImportError:
    print("Warning: Could not import folder_paths from ComfyUI")
    folder_paths = None

NODE_CLASS_MAPPINGS = {
    **FLUXSTART_NODE_MAPPINGS,
    **SDXLSTART_NODE_MAPPINGS,
    **SD35START_NODE_MAPPINGS,
    **QWENIMAGESTART_NODE_MAPPINGS,
    **STARUPSCALE_NODE_MAPPINGS,
    **STARWILDS_NODE_MAPPINGS,
    **STARWILDSADV_NODE_MAPPINGS,
    **FLUXSTARSAMPLER_NODE_MAPPINGS,
    **SDSTARSAMPLER_NODE_MAPPINGS,
    **STARFLUXFILLER_NODE_MAPPINGS,
    **STARNEWS_NODE_MAPPINGS,
    **STARTEXTFILTER_NODE_MAPPINGS,
    **DETAILSTARDAEMON_NODE_MAPPINGS,
    **STARNODE_NODE_MAPPINGS,
    **STARNODE2_NODE_MAPPINGS,
    **STARTEXTINPUT_NODE_MAPPINGS,
    **STARFACELOADER_NODE_MAPPINGS,
    **STARLATENTINPUT_NODE_MAPPINGS,
    **STARLATENTINPUT2_NODE_MAPPINGS,
    **STARIMAGE2LATENT_NODE_MAPPINGS,
    **STARDIVISIBLEDIMENSION_NODE_MAPPINGS,
    **STARLORA_NODE_MAPPINGS,
    **STARPSDSAVER_NODE_MAPPINGS,
    **STARPSDSAVER2_NODE_MAPPINGS,
    **STARTEXTSTORAGE_NODE_MAPPINGS,
    **STARDENOISESLIDER_NODE_MAPPINGS,
    **STARSAMPLERSETTINGS_NODE_MAPPINGS,
    **ASPECTRATIO_NODE_MAPPINGS,
    **ASPECTRATIOADV_NODE_MAPPINGS,
    **STARCOND_IO_NODE_MAPPINGS,
    **STARINFINITEYOU_NODE_MAPPINGS,
    **STARINFINITEYOU_PATCH_NODE_MAPPINGS,
    **STARINFINITEYOU_ADV_PATCHMAKER_NODE_MAPPINGS,
    **STARINFINITEYOU_FACESWAP_MOD_NODE_MAPPINGS,
    **STARGRIDCOMPOSER_NODE_MAPPINGS,
    **STARGRIDBATCHERS_NODE_MAPPINGS,
    **STARWATERMARK_NODE_MAPPINGS,
    **STARPALETTEEXTRACTOR_NODE_MAPPINGS,
    **STAR_RANDOM_IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_CLASS_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_CLASS_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_CLASS_MAPPINGS,
    **STAR_ICON_EXPORTER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_IMAGE_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_CLASS_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_EDIT_ENCODER_NODE_CLASS_MAPPINGS,
    **STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_CLASS_MAPPINGS,
    **STAR_SAVE_FOLDER_STRING_NODE_CLASS_MAPPINGS,
    **STAR_OLLAMA_SYSPROMPTER_JC_NODE_CLASS_MAPPINGS,
    **STAR_NANO_BANANA_NODE_CLASS_MAPPINGS,
    **STAR_DUPLICATE_MODEL_FINDER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_REBALANCE_PROMPTER_NODE_CLASS_MAPPINGS,
    **STAR_QWEN_REGIONAL_PROMPTER_NODE_CLASS_MAPPINGS,
    **STAR_SAMPLER_NODE_CLASS_MAPPINGS,
    **STAR_SIMPLE_FILTERS_NODE_CLASS_MAPPINGS,
    # Manual add for Star Detail Enhancer
    "AdaptiveDetailEnhancement": STARDETAILENHANCER_NODE_MAPPINGS["AdaptiveDetailEnhancement"],
    # Manual add for StarShowLastFrame
    "Star_Show_Last_Frame": STARSHOWLASTFRAME_NODE_MAPPINGS["Star_Show_Last_Frame"],
    # Manual add for StarAspectVideoRatio
    "Starnodes_Aspect_Video_Ratio": STARASPECTVIDEORATIO_NODE_MAPPINGS["Starnodes_Aspect_Video_Ratio"],

}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FLUXSTART_NODE_DISPLAY_NAMES,
    **SDXLSTART_NODE_DISPLAY_NAMES,
    **SD35START_NODE_DISPLAY_NAMES,
    **QWENIMAGESTART_NODE_DISPLAY_NAMES,
    **STARUPSCALE_NODE_DISPLAY_NAMES,
    **STARWILDS_NODE_DISPLAY_NAMES,
    **STARWILDSADV_NODE_DISPLAY_NAMES,
    **FLUXSTARSAMPLER_NODE_DISPLAY_NAMES,
    **SDSTARSAMPLER_NODE_DISPLAY_NAMES,
    **STARFLUXFILLER_NODE_DISPLAY_NAMES,
    **STARNEWS_NODE_DISPLAY_NAMES,
    **STARTEXTFILTER_NODE_DISPLAY_NAMES,
    **DETAILSTARDAEMON_NODE_DISPLAY_NAMES,
    **STARNODE_NODE_DISPLAY_NAMES,
    **STARNODE2_NODE_DISPLAY_NAMES,
    **STARTEXTINPUT_NODE_DISPLAY_NAMES,
    **STARFACELOADER_NODE_DISPLAY_NAMES,
    **STARLATENTINPUT_NODE_DISPLAY_NAMES,
    **STARLATENTINPUT2_NODE_DISPLAY_NAMES,
    **STARIMAGE2LATENT_NODE_DISPLAY_NAMES,
    **STARDIVISIBLEDIMENSION_NODE_DISPLAY_NAMES,
    **STARLORA_NODE_DISPLAY_NAMES,
    **STARPSDSAVER_NODE_DISPLAY_NAMES,
    **STARPSDSAVER2_NODE_DISPLAY_NAMES,
    **STARTEXTSTORAGE_NODE_DISPLAY_NAMES,
    **STARDENOISESLIDER_NODE_DISPLAY_NAMES,
    **STARSAMPLERSETTINGS_NODE_DISPLAY_NAMES,
    **ASPECTRATIO_NODE_DISPLAY_NAMES,
    **ASPECTRATIOADV_NODE_DISPLAY_NAMES,
    **STARCOND_IO_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_PATCH_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_ADV_PATCHMAKER_NODE_DISPLAY_NAMES,
    **STARINFINITEYOU_FACESWAP_MOD_NODE_DISPLAY_NAMES,
    **STARGRIDCOMPOSER_NODE_DISPLAY_NAMES,
    **STARGRIDBATCHERS_NODE_DISPLAY_NAMES,
    **STARWATERMARK_NODE_DISPLAY_NAMES,
   **STARPALETTEEXTRACTOR_NODE_DISPLAY_NAMES,
    **STAR_RANDOM_IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAVE_PANORAMA_JPEG_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_FRAME_FROM_VIDEO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_LOADER_1BY1_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_ICON_EXPORTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_IMAGE_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_WAN_RATIO_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_APPLY_OVERLAY_DEPTH_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_IMAGE_EDIT_INPUTS_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_EDIT_ENCODER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_IMAGE_EDIT_QWEN_KONTEXT_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAVE_FOLDER_STRING_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_OLLAMA_SYSPROMPTER_JC_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_NANO_BANANA_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_DUPLICATE_MODEL_FINDER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_EDIT_PLUS_CONDITIONER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_REBALANCE_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_QWEN_REGIONAL_PROMPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SAMPLER_NODE_DISPLAY_NAME_MAPPINGS,
    **STAR_SIMPLE_FILTERS_NODE_DISPLAY_NAME_MAPPINGS,
    # Manual add for Star Detail Enhancer
    "AdaptiveDetailEnhancement": STARDETAILENHANCER_NODE_DISPLAY_NAMES["AdaptiveDetailEnhancement"],
    # Manual add for StarShowLastFrame
    "Star_Show_Last_Frame": STARSHOWLASTFRAME_NODE_DISPLAY_NAMES["Star_Show_Last_Frame"],
    # Manual add for StarAspectVideoRatio
    "Starnodes_Aspect_Video_Ratio": STARASPECTVIDEORATIO_NODE_DISPLAY_NAMES["Starnodes_Aspect_Video_Ratio"],

}

__version__ = "1.7.0"

# Define the web directory for ComfyUI to find our JavaScript files
WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']

# Define custom types for ComfyUI
def get_custom_types():
    return {
        "SDSTAR_SETTINGS": {"description": "Settings for SDstarsampler"},
        "FLUXSTAR_SETTINGS": {"description": "Settings for Fluxstarsampler"}
    }

# Add custom types to ComfyUI
try:
    import comfy.custom_types
    comfy.custom_types.ensure_custom_types(get_custom_types())
except ImportError:
    print("Warning: Could not register custom types for StarNodes settings")

# Copy wildcards folder to ComfyUI main directory if it doesn't exist
def copy_wildcards_folder():
    if folder_paths is None:
        print("Warning: Could not copy wildcards folder because folder_paths is not available")
        return
    
    # Get the path to the main ComfyUI directory
    comfyui_base_path = folder_paths.base_path
    
    # Get the path to the wildcards folder in the StarNodes extension
    current_dir = os.path.dirname(os.path.abspath(__file__))
    source_wildcards_path = os.path.join(current_dir, 'wildcards')
    
    # Get the path to the destination wildcards folder in the main ComfyUI directory
    dest_wildcards_path = os.path.join(comfyui_base_path, 'wildcards')
    
    # Check if the wildcards folder already exists in the main ComfyUI directory
    if not os.path.exists(dest_wildcards_path):
        try:
            print(f"StarNodes: Copying wildcards folder to {dest_wildcards_path}")
            # Create the destination directory if it doesn't exist
            os.makedirs(dest_wildcards_path, exist_ok=True)
            
            # Copy all files from the source wildcards folder to the destination
            for item in os.listdir(source_wildcards_path):
                source_item = os.path.join(source_wildcards_path, item)
                dest_item = os.path.join(dest_wildcards_path, item)
                
                # Skip if the destination file already exists
                if os.path.exists(dest_item):
                    continue
                
                if os.path.isfile(source_item):
                    shutil.copy2(source_item, dest_item)
                    print(f"StarNodes: Copied wildcard file {item}")
            
            print("StarNodes: Successfully copied wildcards folder to ComfyUI main directory")
        except Exception as e:
            print(f"StarNodes: Error copying wildcards folder: {str(e)}")
    else:
        # Check if we need to copy any missing wildcard files
        for item in os.listdir(source_wildcards_path):
            source_item = os.path.join(source_wildcards_path, item)
            dest_item = os.path.join(dest_wildcards_path, item)
            
            # Skip if the destination file already exists
            if os.path.exists(dest_item):
                continue
            
            if os.path.isfile(source_item):
                try:
                    shutil.copy2(source_item, dest_item)
                    print(f"StarNodes: Copied missing wildcard file {item}")
                except Exception as e:
                    print(f"StarNodes: Error copying wildcard file {item}: {str(e)}")

# Run the copy function when the module is imported
copy_wildcards_folder()

# Serve web assets for StarBetaNodes features
try:
    import json
    from server import PromptServer
    from aiohttp import web

    _OTTERS_DIR = os.path.join(os.path.dirname(__file__), 'web', 'js', 'otters')
    _EDITPROMPTS_PATH = os.path.join(os.path.dirname(__file__), 'editprompts.json')

    @PromptServer.instance.routes.get("/starnodes/otters/{filename:path}")
    async def starnodes_serve_otter_sprite(request):
        filename = request.match_info['filename']
        safe_name = os.path.basename(filename)
        target = os.path.join(_OTTERS_DIR, safe_name)
        if os.path.isfile(target):
            return web.FileResponse(target)
        return web.Response(status=404)

    @PromptServer.instance.routes.get("/starnodes/editprompts")
    async def starnodes_editprompts(request):
        try:
            if os.path.isfile(_EDITPROMPTS_PATH):
                with open(_EDITPROMPTS_PATH, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                return web.json_response(data)
        except Exception as e:
            print(f"Error serving editprompts: {e}")
        return web.json_response({"error": "not found"}, status=404)
except Exception:
    # If server or aiohttp isn't available yet, silently skip
    pass
